### ISSUE TITLE
add aim logger

### ISSUE THREAD

**Issue by ArneBinder** [ChristophAlt/pytorch-ie-hydra-template#43]
config content (this is before #42 and may need adjustment):
```yaml
# https://aimstack.readthedocs.io/en/latest/

aim:
  _target_: aim.pytorch_lightning.AimLogger
  # required because hydra changes the working dir
  repo: ${original_work_dir}/.aim
  experiment: ${replace:${name},/,-}
  train_metric_prefix: train/
  val_metric_prefix: val/

```
